import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by npm run build:widget (source: widget/deskpilot-chat.src.js).
    "extensions/deskpilot-chat/assets/deskpilot-chat.js",
    ".shopify/**",
  ]),
]);

export default eslintConfig;
